name: 04-01 - Exercise - Events
on:
  pull_request:
    types:
      - opened
    branches:
      - main # main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main # main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
      # developer-1
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd 04-react-exercise
          npm ci
      - name: Test code
        run: |
          cd 04-react-exercise
          npm run test
      - name: Build code
        run: |
          cd 04-react-exercise
          npm run build
      - name: Deploy project
        run: echo "Deploying..."